#!/usr/bin/node

import { writeFileSync } from "fs";
import { JSDOM } from "jsdom";

const url = process.argv[2];
const day = process.argv[3];

const text = await (
	await fetch(url, {
		headers: {
			"User-Agent": "github.com/guillaumebrunerie/advent-of-code-2024",
		},
	})
).text();
const dom = new JSDOM(text);

const testInputs = [];
for (const pre of dom.window.document.querySelectorAll("pre")) {
	const testInput = pre.textContent;
	if (!testInputs.includes(testInput)) {
		testInputs.push(testInput);
	}
}

if (testInputs.length == 1) {
	const testInput = testInputs[0];
	writeFileSync(`${day}/testInput.txt`, testInput);

	process.stderr.write(`
Test input:
${testInput}
`);
	console.log(`\t{ file: "${day}/testInput", label: "Test input" },`);
} else {
	testInputs.forEach((testInput, i) => {
		writeFileSync(`${day}/testInput${i + 1}.txt`, testInput);
		process.stderr.write(`
Test input #${i + 1}:
${testInput}
`);
	});
	console.log(
		`\t{ file: "${day}/testInput${i + 1}", label: "Test input #${i + 1}" },`,
	);
}
